language: node_js

sudo: false

node_js: stable

cache:
  yarn: true
  directories:
    - node_modules

before_script:
- yarn global add coveralls nyc

script:
  - yarn test && yarn lint

after_success:
  - nyc report --reporter=text-lcov | coveralls