language: node_js

sudo: false

node_js: stable

cache:
  yarn: true
  directories:
    - node_modules

before_script:
- npm install -g coveralls nyc

script:
  - npm run test && npm run lint

after_success:
  - nyc report --reporter=text-lcov | coveralls